#!/usr/bin/env python3
"""
build_voices.py — bake voice-over clips into voices.js as base64 data URIs.

How to use:
  1) Put audio clips in a ./voices/ folder next to this script, named by category:
        voices/hit1.mp3   voices/hit2.mp3   voices/hit3.mp3      (minor hits)
        voices/great1.mp3 voices/great2.mp3 ...                   (good shots / kills)
        voices/big1.mp3   voices/big2.mp3   ...                   (bullseyes / combos / big moments)
     .mp3, .ogg, .wav and .m4a are all supported.
  2) Run:  python build_voices.py
  3) Reload the games — the announcer now uses YOUR clips (picked at random per category),
     fully embedded so the project stays self-contained. No clips for a category => it
     falls back to the browser's spoken voice for that category.
"""
import base64, glob, json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
VOICES = os.path.join(HERE, "voices")
KINDS = ["hit", "great", "big"]
MIME = {".mp3": "audio/mpeg", ".ogg": "audio/ogg", ".wav": "audio/wav", ".m4a": "audio/mp4"}

def main():
    if not os.path.isdir(VOICES):
        print(f"No ./voices/ folder found at {VOICES}")
        print("Create it and add hit*/great*/big* audio files, then run again.")
        sys.exit(1)

    out, counts, total_bytes = {}, {}, 0
    for kind in KINDS:
        clips = []
        files = sorted(f for f in glob.glob(os.path.join(VOICES, kind + "*"))
                       if os.path.splitext(f)[1].lower() in MIME)
        for f in files:
            ext = os.path.splitext(f)[1].lower()
            data = open(f, "rb").read()
            total_bytes += len(data)
            b64 = base64.b64encode(data).decode("ascii")
            clips.append(f"data:{MIME[ext]};base64,{b64}")
        out[kind] = clips
        counts[kind] = len(clips)

    if sum(counts.values()) == 0:
        print("Found ./voices/ but no clips matching hit*/great*/big*. Nothing to embed.")
        sys.exit(1)

    js = "// AUTO-GENERATED by build_voices.py — embedded voice-over clips.\n"
    js += "window.__voiceClips = " + json.dumps(out) + ";\n"
    with open(os.path.join(HERE, "voices.js"), "w", encoding="utf-8") as fh:
        fh.write(js)

    print("Wrote voices.js")
    for k in KINDS:
        print(f"  {k:<6} {counts[k]} clip(s)")
    print(f"  total audio embedded: {total_bytes/1024:.0f} KB")
    if total_bytes > 4_000_000:
        print("  (heads-up: that's a large JS file — consider shorter/compressed clips)")

if __name__ == "__main__":
    main()
